export const SUBSCRIBE_VALUE_UPDATES = 'SUBSCRIBE_VALUE_UPDATES'
export const UPDATE_VALUE = 'UPDATE_VALUE'
export const INCREASE_SUCCESS = 'INCREASE_SUCCESS'
export const INCREASE_FAILURE = 'INCREASE_FAILURE'
