export const SUBSCRIBE_VALUE_UPDATES = 'SUBSCRIBE_VALUE_UPDATES'
export const UPDATE_VALUE = 'UPDATE_VALUE'
export const SET_CONNECTION_STATUS = 'SET_CONNECTION_STATUS'

export const SOCKET_CREATED = 'SOCKET_CREATED'
export const SOCKET_CLOSED = 'SOCKET_CLOSED'

export const INCREASE_SUCCESS = 'INCREASE_SUCCESS'
export const INCREASE_FAILURE = 'INCREASE_FAILURE'

export const RESET_SUCCESS = 'RESET_SUCCESS'
export const RESET_FAILURE = 'RESET_FAILURE'
